
public enum ServerToClientMsg {
	OPEN_ENTRY_GATE,
	OPEN_EXIT_GATE,
	CLOSE_ENTRY_GATE,
	CLOSE_EXIT_GATE,
	SET_ENTRY_GATE_LED_GREEN,
	SET_ENTRY_GATE_LED_RED,
	SET_EXIT_GATE_LED_GREEN,
	SET_EXIT_GATE_LED_RED,
	SET_SLOT_LED_ON,
	SET_SLOT_LED_OFF,
	SERVERTOCLIENTMSG_MAX
}
