package com.lge.sureparksystem.view;

public enum RequestData {
    // Login
    CREATE_NEW_DRIVER, LOGIN_USER,

    // Driver
    RESERVATION_INFO_REQUEST, PARKINGLOT_INFO_REQUEST, RESERVATION_REQUEST, CANCEL_REQUEST,

    // Attendant
    PARKING_LOT_STATUS_REQUEST,
    
    // Owner
    CHANGE_PARKINGFEE, CHANGE_GRACEPERIOD, REMOVE_PARKINGLOT,CREATE_ATTENDANT, ADD_PARKINGLOT, PARKINGLOT_STATS_REQUEST,
}
